import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeTogglebutton from "@/components/ui/ThemeToggle";
import { Toaster } from "@/components/ui/sonner";
import CanvasCursor from "@/components/CursorCanvas";

const font = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs + Shadcn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <ThemeTogglebutton className="absolute top-2 right-6 z-[100]" />
          {children}
          <CanvasCursor />
          <Toaster richColors position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
